---
title: "Situaciones Especiales"
subtitle: "Una estrategia pro-sistémica"
author: "AP"
date: "`r Sys.Date()`"
output:
  tint::tintPdf: 
    citation_package: natbib
    latex_engine: pdflatex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tint)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tint'))
options(htmltools.dir.version = FALSE)
```



# Resumen de la estrategia

‘Situaciones Especiales’  es una estrategia pro- sistémica. Consiste en comprar activos de importancia estratégica en momentos de pánico, yendo en contra del consenso de mercado. Estos activos de valor estratégico - pero cuya vulnerabilidad los lleva a sufrir crisis recurrentes - son casi siempre rescatados por el sistema capitalista, para evitar contagios  que  pongan en peligro al sistema económico mundial. Luego de pasar por esas crisis vuelven a  un valor de equilibrio y continúan  devengando  las primas de mercado de acuerdo  a su relación riesgo / retorno. Esta filosofía de inversión ‘contrarian’ es un negocio de expectancia positiva, y que agrega diversificación a las  fuentes de retorno al portafolio.
El retorno anualizado esperado es de 10%, y el capital asignado es un 10% del portafolio.

# Activos de importancia estratégica

Los activos de importancia estratégica representan grandes mercados potenciales (Latinoamérica); los gobiernos dependen de ellos para no caer en crisis (petróleo); ocupan un lugar central en la industria (cobre); su valor impacta en grandes masas demográficas (economía de Indonesia) ; o generan un riesgo alto de contagio mercados  de capital centrales (economía de India y China).  

En el  sistema capitalista funciona una red de contención compuesta por  instituciones formales  e informales. En momentos de crisis - y en especial si  son crisis sistémicas - la red de contención preserva los activos de importancia estratégica a través de rescates financieros. Sin ella, la estabilidad del sistema es baja , por lo cual el valor de los activos estratégicos depende directamente de éstas  intervenciones.  
  
```{marginfigure}
Los principales indicadores para monitorear posibles situaciones especiales son: el descuento del valor libros / costo de reposición para acciones;  la alta tasa de retorno de un bono neto de defaults y de recupero ; el nivel del tipo de cambio real multilateral en monedas para hacer el ‘carry trade’; y los precios de ‘break-even’ de la industria de  commodities.

```
  
La calidad de estos activos es baja si se analiza desde la perspectiva del ‘value tradicional’ (que busca retornos altos sobre el patrimonio  con flujos de caja  constantes y estables).  Como las ganancias y los flujos son totalmente impredecibles, la estimación de valor se hace con indicadores más duros y más simples.Además, la jurisdicción de estos activos están manejadas por instituciones extractivas.   


La idea central es invertir cuando haya un muy  fuerte desvío de los indicadores con respecto a su nivel histórico y con respecto al nivel adecuado para la toma de riesgo empresario.  

A diferencia de las estrategias de primas de mercado, en donde buscamos un nivel de entrada promedio, en esta estrategia buscamos un nivel de entrada de alto descuento. El descuento es sobre un valor que ya no es indiscutible, sino que es un paradigma que puede dejar de ser válido. Pero cuando la red de contención interviene, el regreso al valor promedio es a muy alta velocidad para volver a  su valor intrínseco y así devengar las primas de mercado.

# Composición del valor intrínseco

```{marginfigure}
El valor intrínseco es el valor 'duro', más el valor económico, más un put contra el sistema capitalista.

```
El valor intrínseco de esta clase de activos tiene tres componentes, que son (en orden de menor a mayor opcionalidad):
un ‘valor libros’. Este es su valor ‘duro’: su hoja de balance, su PPE, licencias, marcas, intangibles, el valor de los claims y otros. 
un ‘valor económico’ por el free cash-flow que genera y su crecimiento, más la prima de mercado de acuerdo a su concentración  (e.g. mercados emergentes que dependen de commodities).
Un ‘put’ que representa el compromiso del mercado de capitales a salvarlo si sufriera una crisis que ponga en riesgo el sistema capitalista

# Timeline de la inversión

El precio del activo oscila por alrededor del valor intrínseco y tiende a un valor que remunere el riesgo empresario ( 0.8%, 1.8% y 5% para bonos cortos, bonos largos y acciones respectivamente) más un retorno extra por el riesgo de concentración. Cuando el precio perfora el valor ‘duro’ comienza una crisis y luego se produce pánico, porque la posibilidad de un cambio de paradigma es cierta.En el pánico el consenso del mercado exacerba la tendencia bajista y se desprende del activo. Todos tratan de vender al mismo tiempo y no hay liquidez.

En este momento de pánico los inversores ‘contrarian’ compran porque su análisis los lleva a creer que el consenso está equivocado. El contrarían busca un punto de entrada luego de que se produzcan exageraciones en los indicadores que monitorea. La paciencia para esperar el correcto punto de entrada es fundamental para evitar tomar decisiones usando como dato solamente los precios inmediatos anteriores (recency bias).

Una vez tomado el riesgo de invertir, los resultados pueden ser tres:

- El activo es rescatado por el sistema capitalista mundial, con ayuda
Aceleración hacia el valor de equilibrio anterior directa o indirecta. En este caso se ejerció el put. El precio vuelve a la tendencia anterior a la crisis, y esto hace que la aceleración del retorno sea muy alta (pendiente de la línea verde). Antes de eso es probable que el trade sufre un ‘drawdown’ importante, por lo que es una posición difícil de sobrellevar. El consenso piensa lo opuesto de lo que piensa el ‘contrarian’ y su presión es muy grande.

- Value trap: el activo se estabiliza en un nuevo nivel de equilibrio que es más bajo que el anterior. Es probable que no haya retorno o que haya pérdidas. Para evitar una pérdida completa se puede diversificar las activos, a costa de resignar la opcionalidad de multiplicar más veces el retorno.

- El trade quiebra y pierde el 100% de su valor.

# La matemática contrarian: el valor de esperar y la aceleración de retornos

Esta estrategia no tiene control de riesgo estadístico. Pero es valioso ver los números de retorno y de máxima caída para comprender por qué la ideología ‘contrarian’ funciona, y también para saber qué esperar en el ‘mark to market’ y entonces prepararse para afrontar los problemas de governance que genere.
Como vimos los resultados de invertir en un activo en crisis pueden ser tres, y los repasamos con la siguiente tabla de doble entrada. 
Supongamos que hay un activo que vale A$100 y que ése es su valor intrínseco: 
Los retornos de los trades ganadores tienen una aceleración exponencial. El retorno que generan - entre 3x y 10x el patrimonio - cubre el resultado negativo del resto de los trades.

Los salvatajes financieros aceleran la vuelta al nivel de primas de retorno promedio, de la misma manera que las crisis aceleran el cambio de paradigma.  Cuanta más paciencia se tenga para esperar  los momentos de concentración e iliquidez, mayor es el rédito de este sistema.

Esto es así porque hay crisis que son tan profundas que el abandono del paradigma anterior es una certeza  para el consenso. El inversor contrarían es el único que cree en la probabilidad de una vuelta al estado anterior. Cuanto más seguro está de su análisis más puede esperar el pánico del consenso. A mayor descuento mayor aceleración posterior y mayor opcionalidad a favor. Este sistema no tiene que ver con devengar primas de mercado: tiene que ver con aprovechar la opcionalidad que da el sistema capitalista.

El  gráfico anterior muestra  el efecto de entrar con un 70%, un 80% o un 90% de máxima caída del valor intrínseco anterior (que no existe más en la cabeza del consenso pero es una de las opciones que tiene el contrarían en su hipótesis).

Sobretodo hay que observar la diferencia entre entrar a $20 y a $10.  Esto muestra dos cosas:
1- que el valor de esperar es muy alto cuando las crisis son muy profundas. 2- que explotar concentración e liquidez depende en gran parte la habilidad en el ‘timing’ de entrada y de salida. Si no hay valor intrínseco el timing define si un trade es excelente, regular o malo.

# Alocación dentro del portafolio

Algunos trades ganadores multiplican su capital de manera de cubrir los trade de quiebra y los value trap. No es una estrategia para aplicar al mucho  capital: el costo emocional de ser contrarian es muy alto y genera grandes problemas de governance, las caídas son muy visibles (aunque se escoja hacer ‘mark to model’) y la alineación con el management es opuesta a los intereses del inversor (por la misma opcionalidad que la explota). Sin embargo, aprovechar rescates sistémicos es una  fuente válida de retorno y difiere conceptualmente con el resto de las estrategias, por lo tanto es bueno sumarla a un  portafolio de otras ideas.

La propuesta es destinar un 10% del total del portafolio. Mientras no haya situaciones que explotar, el capital destinado a la estrategia permanecerá en el resto del portafolio.
Esperamos que cada trade madure en períodos largos - 3 años o más - culminando cuando el gap entre el precio de mercado y el valor intrínseco de los activos vuelva a un nivel de equilibrio, sea el nivel pre-crisis o uno nuevo. La única excepción es si la velocidad de recupero de un  trade ganador es muy alta . En ese caso, el capital del trade se asignará a un mejor uso.

La alocación de capital a cada trade dependerá de las expectativas de riesgo / retorno de la situación especial. En general, la alocación será más grande, si el descuento contra el valor duro es muy importante y  si la convicción sobre la idea es alta . También influye la alta o baja complejidad económica de la situación.

# Control de riesgo

El control de riesgo no es estadístico y al ser activos listados la valuación ‘mark  to market’ va a ser muy variable sobre todo al inicio de cada posición. Por eso es mejor pensar en ellos como en un negocio de  valuación “mark to model” (seguimiento de las premisas de flujos y no de los precios). 
Las medidas de máxima caída o volatilidad no deben usarse y frente a la ausencia de control sistemático de riesgo es importante apoyarse en la robustez y la simpleza del análisis para soportar los momentos de pérdidas. Aumenta el riesgo del portafolio medido como máxima caída y aumenta el riesgo de correlación estadística entre estrategias porque el máximo stress se dará al mismo tiempo que el resto de las estrategias de mercado. Creemos que la máxima caída puede aumentar en un 5%.